### ISSUE TITLE
Optional homework for imports

### ISSUE THREAD

**Issue by VladFiliucov** [meenaHaque/frontend-superheros#3]
So at the moment we are rendering our superheroes inside our `App` component as an unordered list. Let's extract our superheroes rendering logic into a separate component called `Superheroes` and import it in our App component. Our App component is going to look something like this 
```
<div className="App">
  <Superheroes />
</div>
```
This also means that we can write a test for Superheroes component without rendering whole application. But this is also optional of course ;)

**Comment by meenaHaque** [comment]
Done
